controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - j_base_2
      - j_lower_arm_3
      - j_upper_arm_3
      - j_gripper_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - j_gripper_claw_1
      - j_gripper_claw_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
