move_group:
  ros__parameters:
    default_velocity_scaling_factor: 0.1
    default_acceleration_scaling_factor: 0.1

    joint_limits:
      j_base_2:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: false
        max_acceleration: 0.0

      j_gripper_4:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: false
        max_acceleration: 0.0

      j_lower_arm_3:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: false
        max_acceleration: 0.0

      j_upper_arm_3:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: false
        max_acceleration: 0.0

      j_gripper_claw_1:
        has_position_limits: true
        min_position: -0.48
        max_position: 0.30
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: false
        max_acceleration: 0.0

      j_gripper_claw_2:
        has_position_limits: true
        min_position: -0.30
        max_position: 0.48
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: false
        max_acceleration: 0.0

