move_group:
  ros__parameters:
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - arm_controller
        - joint_controller
        
      arm_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - j_base_2
          - j_lower_arm_3
          - j_upper_arm_3
          - j_gripper_4
          
      joint_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: false
        joints:
          - j_gripper_claw_1
          - j_gripper_claw_2
         
########################################################################################
# MoveIt uses this configuration for controller management

##moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

##moveit_simple_controller_manager:
##  controller_names:
##    - arm_controller

##  arm_controller:
##    type: FollowJointTrajectory
##    joints:
##      - j_base_2
##      - j_lower_arm_3
##      - j_upper_arm_3
##      - j_gripper_4

